### ISSUE TITLE
lsdsng-import should ignore .WM.lsdsng in filename

### ISSUE THREAD

**Issue by urbster1** [stijnfrishert/libLSDJ#56] opened 2019-06-27 03:12 UTC
if more than 1 lsdsng is imported, just put the first one in working memory. as-is, WM files don't append to the save file and if more than 1 WM lsdsng is imported, one of them gets lost.

**Comment by stijnfrishert** [comment] 2019-07-10 10:04
- What do you mean with "don't append"?
 - If more than one WM lsdsng is imported I'd argue you're doing something weird in the first place :p

But yeah, makes sense to just select the first lsdsng as WM. Why just with more than 1 though?

**Comment by urbster1** [comment] 2019-07-10 13:56
I had 2 saves and I wanted to merge them together and use the songs in
working memory from both, that's why. Found out that one of them got placed
into working memory only, but not the save itself, and the other one didn't
add at all. Maybe it's worth checking to see if 2 song names are identical
but one has WM and the other doesn't?

**Comment by rbong** [comment] 2020-02-09 21:10
It seems like this is another issue I can handle

**Comment by stijnfrishert** [comment] 2020-02-09 22:50
Sure, I'd say go ahead! Are we all agreeing that it's a good thing the import tool should ignore the working memory song (@rbong I'm assuming you've worked with the tools and lsdj before)?

**Comment by urbster1** [comment] 2020-02-09 23:14
if you're asking me, i'd prefer for anything with .wm in the filename be
ignored and for the first song in the input to go into working mem. but
maybe a flag makes more sense. the main issue here i think was that if you
have two songs that are .wm songs, one of them gets ignored, so at least
that behavior should probably be changed

**Comment by rbong** [comment] 2020-02-16 14:37
I've been thinking more about this issue and I think this would be the most flexible behaviour:

  - Provide a flag to explicitly put a song into working memory
  - Ignore the `.WM` extension and treat these like regular `.lsdsng` files
  - Do not put a song into working memory otherwise

Tried to think of something we could do to guess what the user is trying to do but I don't think you can account for every case without explicit flags.

**Comment by rbong** [comment] 2020-02-16 16:36
Just realized that we might have to guess/provide some options for working with directories. If the user specifies `lsdj-import -o lsdj.sav --working-file folder/file.WM.lsdsng folder/` and we're treating the `WM` file as a regular file, the `WM` file will be placed in its own save file as well as working memory, which may or may not be the user's intention. Open to solutions.

**Comment by stijnfrishert** [comment] 2020-02-18 09:37
Right, I fully agree with your original original idea; just add a flag to explicitly set a working memory song and otherwise simply don't. Guessing for the user always ends up generating problems in edge cases.

If a folder contains a .WM it would be put in its own slot, at which point I think we shouldn't export it on default in `lsdsng-export` (or at the very least don't if the file_changed flag isn't set).

In regards to your second comment: why don't we simply check for duplicates?

**Comment by stijnfrishert** [comment] 2020-02-18 09:37
(Accidentally closed)

**Comment by rbong** [comment] 2020-02-18 17:40
>In regards to your second comment: why don't we simply check for duplicates?

That's a good idea. To expand on this idea a little bit, I think this behaviour would make sense when importing folders:

  - Check folder for names in the form `*.wm.lsdsng`
  - When one is found, if a working song wasn't specified, no working song was already found, and it's not a duplicate of any file in the folder, use it as the working memory song
  - Otherwise, skip `*.wm.lsdsng` files in folders and print that we are skipping them as well as whether they are duplicates

There is a bunch of other prioritization we can potentially do but it's better if we rely on making the user specify the working memory file or just rely on them putting the appropriate folder first.
We can potentially add flags for changing this behaviour in the future but I think users will usually want to skip most `*.wm.lsdsng` files when importing multiple folders, or even multiple `*.wm.lsdsng` files in a single folder.

Let me know what you think.

**Comment by stijnfrishert** [comment] 2020-02-19 14:44
Completely agree on this. And if we (good suggestion) just print out we skipped a couple of files, they'll know and it's up to users to select which WM song they *do* want with the flag.

**Comment by stijnfrishert** [comment] 2020-02-26 22:06
@rbong I'm slowly nearing a v2.0.0 release (gotta rethink the error API and waiting for some test files from @urbster1).

Do you want this issue to get in v2.0.0 as well (I'm assuming you're working on this)?

**Comment by rbong** [comment] 2020-02-26 22:15
@stijnfrishert If you can wait a couple of weeks, this can go in v2.0.0

**Comment by stijnfrishert** [comment] 2020-02-27 10:31
Hm, I hope to release sooner than that, but then we'll just add this to v2.1.0. :)

No rush either way, just wanted to know what milestone to put this under.

**Comment by stijnfrishert** [comment] 2020-11-09 08:46
@rbong Any news on this?

If you can't find the time right now that's fine, in which case I might tackle this for the upcoming release (I've found some spare time/motivation lying around :p)

**Comment by rbong** [comment] 2020-11-09 18:18
No progress on this, sorry. This fell off my radar.

**Comment by stijnfrishert** [comment] 2020-11-09 19:29
No problem, thanks for letting me know :)

**Comment by stijnfrishert** [comment] 2020-11-10 16:54
* Importer now has a --working-memory flag to provide the working memory song.
 * All .WM files are ignored
   * Only in a folder. When you provide it manually it's just another project slot

Does that work for you, @urbster1?

**Closed by stijnfrishert** 2020-11-10 16:54 UTC
Labels: enhancement

**Comment by urbster1** [comment] 2020-11-10 17:49
Sure
